#!/bin/bash

BACKUP_DIR="$HOME/tools/proj_backups"
PROJECTS_DIR="$HOME/Projects"
DATE=$(date +%Y%m%d)

mkdir -p "$BACKUP_DIR"

count=0
for project in "$PROJECTS_DIR"/*/; do
    PROJECT_NAME=$(basename "$project")
    echo "Backing up $PROJECT_NAME..."

    PROJECT_PATH="${project%/}"

    tar -czf "$BACKUP_DIR/${PROJECT_NAME}_${DATE}.tar.gz" \
        --exclude="vendor" \
        --exclude="node_modules" \
        --exclude=".git" \
        "$PROJECT_PATH"

    if [[ $? -eq 0 ]]; then
        ((count++))
    else
        echo "Failed to back up $PROJECT_NAME"
    fi
done

find "$BACKUP_DIR" -name "*.tar.gz" -mtime +14 -delete

echo "Backup complete! Backed up $count projects"
