#!/bin/bash

BACKUP_DIR="$HOME/backups"
DATE=$(date +%Y%m%d)

mkdir -p "$BACKUP_DIR"

for project in ~/Projects/*/; do
    PROJECT_NAME=$(basename "$project")
    
    echo "Backing up $PROJECT_NAME..."
  
    # Dont include vendor, node mods etc. Add any others here. 
    tar -czf "$BACKUP_DIR/${PROJECT_NAME}_${DATE}.tar.gz" \
        --exclude="vendor" \
        --exclude="node_modules" \
        --exclude=".git" \
        "$project"
done

# Delete older than 14 days
find "$BACKUP_DIR" -name "*.tar.gz" -mtime +14 -delete

echo "Backup complete! Backed up $(ls ~/projects | wc -l) projects"
echo "ADD THE README!!!!!!!!!!"
