#!/bin/bash

read -p "What is the name of the root direvtory you want the git stats for? " ROOT_DIRECTORY

cd "../Projects/$ROOT_DIRECTORY" || {
    echo "Directory $ROOT_DIRECTORY does not exist."
    exit 1
}
     
if [ -f $ROOT_DIRECTORY ]; then
   echo "File $ROOT_DIRECTORY exists."
else
   echo "File $FILE does not exist."
fi

git status && git branch && git log --oneline

exit

