#!/bin/bash
PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin"

LOCKDIR="/tmp/gitstats.lockdir"

if ! mkdir "$LOCKDIR" 2>/dev/null; then
    echo "Another instance is running"
    exit 0
fi

trap 'rm -rf "$LOCKDIR"' EXIT

PROJECTS_DIR="$HOME/Projects"
if [ ! -d "$PROJECTS_DIR" ]; then
    echo "No Projects Directory"
    exit 1
fi

LOG_DIR="$HOME/tools/logs"

mkdir -p "$LOG_DIR"

for TARGET in "$PROJECTS_DIR"/*; do
    [ -d "$TARGET" ] || continue

    git -C "$TARGET" rev-parse --is-inside-work-tree >/dev/null 2>&1 || continue
 
    PROJECT_NAME=$(basename "$TARGET")
    LOG_FILE="$LOG_DIR/${PROJECT_NAME}.log"

    # Only 10 logs
    for i in 9 8 7 6 5 4 3 2 1; do
        [ -f "$LOG_FILE.$i" ] && mv "$LOG_FILE.$i" "$LOG_FILE.$((i+1))"
    done

    [ -f "$LOG_FILE" ] && mv "$LOG_FILE" "$LOG_FILE.1"

    dt=$(date '+%d/%m/%Y %H:%M:%S')

    {
        echo "===== $dt ====="
        git -C "$TARGET" fetch 2>&1
        git -C "$TARGET" status
        git -C "$TARGET" branch
        git -C "$TARGET" log --oneline
        echo
    } > "$LOG_FILE"

done

